version: '3.9'
services:
  ecommerce:
    image: postgres:14.1-alpine
    container_name: ecommerce
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
      
volumes:
  db:
    driver: local